### PR TITLE
Build with Swift Package Manager

### PR DESCRIPTION
**Pull request by chkn**
This patch migrates the build to be based on Package.swift and the Swift Package Manager.

First off, sorry for moving everything around. Here's a summary of the state of things:

1. You still need to get the SkiaSharp binaries. Now, you need to put them under `native/{osx,ios,tvos}` - this now matches the directory structure in the zip files you get from Azure pipelines.
2. You can now build for Mac by simply doing `swift build`. This should produce something like `.build/x86_64-apple-macosx/debug/libSkiaKit.dylib`
3. Theoretically `swift build` should work for Linux too, but we probably need to set the linker flags for it to find `libSkiaSharp.so`, either in the `Package.swift` or on the command line, e.g. `swift build -Xlinker -L/foo/bar/baz`. I don't have easy access to Linux at the moment, so I haven't tried it.
4. Ultimately, once Swift Package Manager gets proper support for binary dependencies, you should be able to just add a package reference to this GitHub repo in Xcode and have it work. But for now, we can still build frameworks for iOS and tvOS. This part is slightly hacked together, but running `make xcodeproj` should produce a `SkiaKit.xcodeproj` that can be used to build those. There is a minor linker error about linking a Mac dylib for a simulator build, but I believe that can be ignored (otool shows the correct framework is linked)

### CODE REVIEW

**Comment by migueldeicaza** [comment]
Thank you - I finally tried this and it works wonderfully.

I have a couple of concerns - I do not know how to include the Apple directory only for Apple platforms, nor how would I include platform-specific files (for example, on Mac, I would include NSView support).   And I would like to avoid the Apple bits on Linux.

**Comment by chkn** [comment]
Glad to hear it works!

I’m not sure how to conditionally include files. I was using `#if canImport(...)` as a way to test for things like SwiftUI and UIKit, which I think is a little more robust than platform detection

**Comment by migueldeicaza** [comment]
I am massaging your changes into the existing codebase, purely to keep the existing Xcode setup that works to produce tvOS, macOS, iOS packages workibng

**Comment by migueldeicaza** [comment]
Thank you for this patch - I used this as the foundation for a patch that did not move the files.

**Pull request closed without merging**
